<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php


$indexURL = $block->getUrl("megaventory/index/index");
$formAction = $block->getUrl("megaventory/index/savesettings");

$apikey = $block->getSettingValue('apikey');
$apiurl = $block->getSettingValue('apiurl');
$enabled = $block->getSettingValue('enabled');
$orderSyncrhonization = $block->getSettingValue('ordersynchronization');
if (empty($orderSyncrhonization)) {
    $orderSyncrhonization = '0';
}
$syncTimestamp = $block->getSettingValue('synctimestamp');
$connectivityOk = $block->connectivityOk();

$magentoInstallations = $block->getMagentoInstallations();
$magentoId = $block->getSettingValue('magentoid');

if ($connectivityOk !== true) {
    $actionsDisabled = ' disabled ';
    $buttonOnClick = ' onclick="" ';
} else {
    $actionsDisabled = '';
}

$checkCountsInStock = $block->getUrl("megaventory/index/updateCountsInStock");
$syncIvnentoriesUrl = $block->getUrl("megaventory/index/importInventories");
$stockSourceCollection = $block->getSources();

?>
<style type="text/css">
    .bg-disabled {
        background: #EEE;
    }
    .shrink-col{
        width:15%;
    }
    .remove_source.danger {
        color: #F00;
        margin-left: 0.5rem;
    }
    .modal-inner-wrap .modal-footer .action-primary.custom {
        background-color: #eb5202;
        border-color: #eb5202;
        color: #ffffff;
        text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.25);
    }
</style>
<div id="page:main-container" class="page-columns">
    <div class="admin__old">
        <div id="container" class="main-col">
            <div class="mvsettings-container row">
                <div class="col-m-6">
                    <div class="entry-edit form-inline">
                        <form id="mv_connectivity_form" action="<?= $formAction ?>" method="post" novalidate="novalidate">
                            <?= $block->getBlockHtml('formkey') ?>
                            <fieldset class="fieldset admin__fieldset " id="connectivity_fieldset">
                                <legend class="admin__legend legend">
                                    <span>Connectivity</span>
                                </legend>
                                <br>
                                <?php if (empty($syncTimestamp)) {
                                    if (empty($apikey) || empty($apiurl)) {
                                        ?>
                                        <div id="row_megaventory_link">
                                            If you don't already have a Megaventory Account please <a href="http://megaventory.com/?getstarted=1" target="_blank">Click
                                                Here</a>
                                        </div>
                                        <?php
                                    }
                                } ?>
                                <div class="admin__field field">
                                    <label class="label admin__field-label" for="megaventory_connectivity_enabled-id"> <span> Extension
                                            Status </span></label>
                                    <div class="admin__field-control control">
                                        <select id="megaventory_connectivity_enabled-id" name="megaventory_enabled" class=" select admin__control-select" data-ui-id="system-store-edit-0-form-fieldset-element-select-website-default-group-id">
                                            <option value="1" <?php if ($enabled == '1') { echo ' selected';} ?>>Enabled</option>
                                            <option value="0" <?php if ($enabled == '0') { echo ' selected';} ?>>Disabled</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="admin__field field">
                                    <label class="label admin__field-label" for="megaventory_connectivity_apiurl-id"> <span>API URL</span></label>
                                    <div class="admin__field-control control">
                                        <input id="megaventory_connectivity_apiurl-id" name="megaventory_apiurl" value="<?= $apiurl ?>" type="text" class=" input-text admin__control-text">
                                    </div>
                                </div>
                                <div class="admin__field field">
                                    <label class="label admin__field-label" for="megaventory_connectivity_apikey-id"> <span>API Key</span></label>
                                    <div class="admin__field-control control">
                                        <input id="megaventory_connectivity_apikey-id" name="megaventory_apikey" value="<?= $apikey ?>" type="text" class=" input-text admin__control-text">
                                    </div>
                                </div>
                                <div class="actions" style="text-align: center">
                                    <div id="validation_result" class="message-validation hidden"></div>
                                    <button type="submit">
                                        <span>Update</span>
                                    </button>
                                </div>
                                <div style="text-align: center; margin: 30px;" class="admin__field field">
                                    <?php if ($connectivityOk === true) { ?>
                                        <span id="connectivity-message-id"> Connectivity OK<img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/accept.png') ?>" style="position: relative; top: 1px; left: 4px;" />
                                        </span>
                                    <?php } else { ?>
                                        <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/exclamation.png'); ?>" title="" style="position: relative; top: 1px; right: 4px;" />
                                        <span id="connectivity-message-id">Connectivity Failed.<br /><?= $connectivityOk ?>
                                        </span> <span style="color: red;" id="connectivity-error-message-id"></span>
                                    <?php } ?>
                                </div>
                                <?php if (empty($syncTimestamp)) { ?>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="website_name" data-ui-id="system-store-edit-0-form-fieldset-element-text-website-name-label"><span>Order
                                                Synchronization</span></label>
                                        <div class="admin__field-control control">
                                            <input type="checkbox" disabled id="megaventory_connectivity_order-id" name="megaventory_order_synchronization" class="admin__control-checkbox" /> <label class="admin__field-label" for="megaventory_connectivity_order-id"> This option will be
                                                enabled when the Setup Wizard ends successfully. While this
                                                option is unchecked, no sales orders are sent to Megaventory
                                                from Magento. This option should be enabled only when the
                                                inventory quantities of Magento and Megaventory are
                                                synchronized (after the Setup Wizard ends succesfully).
                                                <br /><br />
                                                <b>Warning:</b> Avoid shipping orders from Magento while having this option enabled because it might generate inconsistencies. Create the shipments in Megaventory and they will be synchronized with Magento automatically.</span> </label>
                                        </div>
                                    </div>
                                <?php } else { ?>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="website_name" data-ui-id="system-store-edit-0-form-fieldset-element-text-website-name-label"><span>Order
                                                Synchronization</span></label>
                                        <div class="admin__field-control control">
                                            <input type="checkbox" <?php if ($orderSyncrhonization === '1') { ?> checked <?php
                                                                   } ?> id="megaventory_connectivity_order-id" onclick="checkOrderSynchronization(this.checked, this);" name="megaventory_order_synchronization" class="admin__control-checkbox" /> <label class="admin__field-label" for="megaventory_connectivity_order-id"> Check this option to
                                                enable order synchronization between Magento and Megaventory.
                                                While this option is unchecked, no sales orders are sent to
                                                Megaventory from Magento. This option should be enabled only
                                                when the inventory quantities of Magento and Megaventory are
                                                synchronized (after the Setup Wizard ends succesfully). 
                                                <br /><br />
                                                <b>Warning:</b> Avoid shipping orders from Magento while having this option enabled because it might generate inconsistencies. Create the shipments in Megaventory and they will be synchronized with Magento automatically.</span> </label>
                                        </div>
                                    </div>
                                <?php } ?>
                            </fieldset>
                        </form>
                    </div>
                </div>

                <div class="col-m-6">
                    <div class="entry-edit form-inline">
                        <form id="mv_setup_form" action="<?= $formAction ?>" method="post" novalidate="novalidate">
                            <?= $block->getBlockHtml('formkey') ?>
                            <fieldset class="fieldset admin__fieldset " id="setup_fieldset">
                                <legend class="admin__legend legend">
                                    <span>Setup Wizard</span>
                                </legend>
                                <?php if (empty($syncTimestamp)) { ?>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_magento_id-id"> <span> Magento Id </span></label>
                                        <div class="admin__field-control control">
                                            <select id="megaventory_magento_id-id" <?php if ($magentoInstallations <= 0) { echo 'disabled'; } ?> name="" class=" select admin__control-select">
                                                <?php
                                                for ($i = 0; $i < $magentoInstallations; $i++) {
                                                    $value = ($i > 0) ? 'magento-' . $i : 'magento';
                                                    ?>
                                                    <option value="<?= $value ?>" <?php if ($magentoId == $value) { echo 'selected'; } ?>>
                                                        <?= 'magento-' . $i ?>
                                                    </option>
                                                    <?php
                                                } ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_shipping_sku-id"> <span>Shipping Product SKU</span></label>
                                        <div class="admin__field-control control">
                                            <input id="megaventory_shipping_sku-id" name="megaventory_shippingproduct" value="<?= $block->getSettingValue('shippingproductsku'); ?>" type="text" class=" input-text admin__control-text"> <span style="display: none; color: red;" class="validation-advice" id="megaventory_shipping_sku-id-required" style="">This is a
                                                required field.</span>
                                        </div>
                                    </div>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_discount_sku-id"> <span>Discount Product SKU</span></label>
                                        <div class="admin__field-control control">
                                            <input id="megaventory_discount_sku-id" name="megaventory_discountproduct" value="<?= $block->getSettingValue('discountproductsku'); ?>" type="text" class=" input-text admin__control-text"> <span style="display: none; color: red" class="validation-advice" id="megaventory_discount_sku-id-required" style="">This is a
                                                required field.</span>
                                        </div>
                                    </div>
                                    <div class="admin__field field">
                                        <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/message.png') ?>" style="position: relative; top: 1px; left: 4px; margin-right: 10px;" />
                                        <span style="font-weight: bold;">If you are using any custom
                                            attribute for supplier management in Magento <br />please fill
                                            in the field below the <font style="color: rgb(187, 32, 32)">attribute
                                                code</font> of this attribute (i.e supplier, manufacturer
                                            etc). <br />Only attributes of frontend type Text or Dropdown
                                            are supported. <br />The field is not mandatory.
                                        </span>
                                    </div>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_supplier-id"> <span>Supplier Attribute Code</span></label>
                                        <div class="admin__field-control control">
                                            <select id="megaventory_supplier-id" name="supplier_attribute_code" class="select admin__control-select">
                                                <?php $attributes = $block->getAttributes(); ?>
                                                <?php foreach($attributes as $attribute): ?>
                                                    <option value="<?= $attribute->getAttributeCode(); ?>" <?= ($block->getSettingValue('supplierattributecode') == $attribute->getCode()) ? 'selected' : '' ?> ><?= $attribute->getFrontendLabel(); ?></option>
                                                <?php endforeach; ?>    
                                            </select>

                                            <?php if (!empty($syncTimestamp)) { ?>
                                                <button id="save-config-btn" type="button" onclick="updateSupplierSettings()">
                                                    <span>Update</span>
                                                </button>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <div>
                                        <span><strong>Initialize Data</strong></span>

                                    </div>
                                    <div>
                                        <div id="sync-data-id">
                                            <span id="sync-heading-id"></span>
                                            <ul id="sync-data-progress-id">

                                            </ul>
                                        </div>
                                    </div>

                                    <div>
                                        <?php if ($connectivityOk === true) {
                                            if ($block->checkBaseCurrencies()) {
                                                ?>
                                                <button id="sync-data-btn" type="button" onclick="javascript:syncData()" <?php if (empty($apikey) || empty($apiurl)) { ?> style="display: none;" <?php
                                                                                                                         } ?>>
                                                    <span> Start </span>
                                                </button>
                                            <?php } else { ?>
                                                <span id="currencies-message-id"> <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/exclamation.png') ?>" style="position: relative; top: 1px;" /> <br />Setup Wizard
                                                    cannot start. <br />You must set your Magento and Megaventory
                                                    default Currencies to the same value. <br />Current default values are <?= $block->getDefaultMagentoCurrency() ?> for Magento and <?= $block->getDefaultMegaventoryCurrency() ?> for Megaventory.
                                                    <br />Please contact <a href="http://megaventory.com/?contact-us=1" target="_blank">Megaventory
                                                        Support</a>
                                                </span>
                                                <?php
                                            }
                                        } else {
                                            ?>
                                            <span id="connectivity-message-id">Connection Failed <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/exclamation.png') ?>" title="<?= $connectivityOk ?>" style="position: relative; top: 1px; left: 4px;" /></span> <span style="color: red;" id="connectivity-error-message-id"></span>
                                        <?php } ?>
                                        <div id="next-step" style="display:none">
                                            <table class='data-grid' data-role='grid' style="margin:1%">
                                                <thead>
                                                    <tr>
                                                        <th>Magento inventory source</th>
                                                        <th>Megaventory location</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php foreach ($stockSourceCollection as $itemSource): ?>
                                                        <tr>
                                                            <td>
                                                                <input type="hidden" class='source' name="sources[]" value="<?= $itemSource->getSourceCode(); ?>" />
                                                                <span><?= $itemSource->getName(); ?></span>
                                                            </td>
                                                            <td>
                                                                <select class='select admin__control-select inventory' name="locations[]">
                                                                </select>
                                                            </td>
                                                        </tr>
                                                    <?php endforeach; ?>
                                                </tbody>                    
                                            </table>            
                                            <button id="export-stock-btn" type="button" style="margin-left: auto; margin-right: auto; display: table" onclick="exportStockAndFinish(0)" disabled>
                                                <span> Export Magento Stock in Megaventory as Megaventory Inventory Adjustment</span>
                                            </button>
                                            &nbsp;
                                            <br /><span id="export-stock-msg"></span>
                                            <br />
                                            <button id="cancel-export-stock" type="button" style="margin-left: auto; margin-right: auto; display: table" onclick="location = '<?= $indexURL ?>';">
                                                <span> Cancel, I will import Megaventory stock manually </span>
                                            </button>

                                            <br>
                                            <button id="finish-btn" type="button" style="display: none;" onclick="javascript:location = '<?= $indexURL ?>';">
                                                <span> Finish </span>
                                            </button>
                                        </div>
                                        <div id="next-error" style="display: none;">
                                            <br>
                                            <button id="error1-data-no-btn" type="button" onclick="javascript:location = '<?= $indexURL ?>';">
                                                <span> Refresh Page </span>
                                            </button>
                                        </div>
                                        <button id="reset-data-btn" type="button" onclick="javascript:resetSetup()" style="display: none;">
                                            <span> Reset Setup </span>
                                        </button>
                                    </div>
                                <?php } else { ?>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_magento_id-id"> <span> Magento Id </span></label>
                                        <div class="admin__field-control control">
                                            <select id="megaventory_magento_id-id" <?php if ($magentoInstallations <= 0) { echo 'disabled'; } ?> name="" class=" select admin__control-select">
                                                <?php
                                                for ($i = 0; $i < $magentoInstallations; $i++) {
                                                    $value = ($i > 0) ? 'magento-' . $i : 'magento';
                                                    ?>
                                                    <option value="<?= $value ?>" <?php if ($magentoId == $value) { echo 'selected'; } ?>>
                                                        <?= 'magento-' . $i ?>
                                                    </option>
                                                    <?php
                                                } ?>
                                            </select>
                                            <?php if ($connectivityOk === true) { ?>
                                                <button id="save-config-btn" type="button" onclick="updateMagentoId()">
                                                    <span>Update</span>
                                                </button>
                                            <?php } else { ?>
                                                <button id="save-config-btn" type="button" class="disabled" onclick="updateMagentoId()">
                                                    <span>Update</span>
                                                </button>
                                            <?php } ?>
                                        </div>

                                    </div>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_shipping_sku-id"> <span>Shipping Product SKU</span></label>
                                        <div class="admin__field-control control">
                                            <input id="megaventory_shipping_sku-id" name="megaventory_shippingproduct" value="<?= $block->getSettingValue('shippingproductsku'); ?>" type="text" class=" input-text admin__control-text"> <span style="display: none" class="validation-advice" id="megaventory_shipping_sku-id-required" style="">This is a
                                                required field.</span>
                                        </div>
                                    </div>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_discount_sku-id"> <span>Discount Product SKU</span></label>
                                        <div class="admin__field-control control">
                                            <input id="megaventory_discount_sku-id" name="megaventory_discountproduct" value="<?= $block->getSettingValue('discountproductsku'); ?>" type="text" class=" input-text admin__control-text"> <span style="display: none" class="validation-advice" id="megaventory_discount_sku-id-required" style="">This is a
                                                required field.</span>
                                        </div>
                                    </div>
                                    <div class="admin__field field">
                                        <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/message.png') ?>" style="position: relative; top: 1px; left: 4px; margin-right: 10px;" />
                                        <span style="font-weight: bold;">If you are using any custom
                                            attribute for supplier management in Magento <br />please fill
                                            in the field below the <font style="color: rgb(187, 32, 32)">attribute
                                                code</font> of this attribute (i.e supplier, manufacturer
                                            etc). <br />Only attributes of frontend type Text or Dropdown
                                            are supported. <br />The field is not mandatory.
                                        </span>
                                    </div>
                                    <div class="admin__field field">
                                        <label class="label admin__field-label" for="megaventory_supplier-id"> <span>Supplier Attribute Code</span></label>
                                        <div class="admin__field-control control">
                                            <select id="megaventory_supplier-id" name="supplier_attribute_code" class="select admin__control-select">
                                                <?php $attributes = $block->getAttributes(); ?>
                                                <?php foreach($attributes as $attribute): ?>
                                                    <option value="<?= $attribute->getAttributeCode(); ?>" <?= ($block->getSettingValue('supplierattributecode') == $attribute->getAttributeCode()) ? 'selected' : '' ?> ><?= $attribute->getFrontendLabel(); ?></option>
                                                <?php endforeach; ?>    
                                            </select> <br>
                                            <button id="save-config-btn" type="button" onclick="updateSupplierSettings()">
                                                <span>Update</span>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="admin__field field">
                                        <strong>Setup Report</strong><br /> <span>
                                            <?= $block->getSettingValue('syncreport'); ?>
                                        </span>
                                    </div>
                                    <div class="admin__field field">
                                        <button id="sync-data-btn" type="button" onclick="javascript:resetSetup()">
                                            <span> Reset Setup </span>
                                        </button>
                                    </div>
                                <?php } ?>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
            <div class="mvsettings-container row" style="height:20px;border-bottom:2px solid grey;margin-bottom:20px;">
            </div>
            <?php if (!empty($syncTimestamp)) { ?>
                <div class="mvsettings-container row">
                    <div class="col-m-12">
                        <div class="admin__legend">Inventory Locations</div>
                        <?php
                        $updateIvnentoryLocationsUrl = $block->getUrl("megaventory/index/updateInventoryLocations");
                        if ($connectivityOk === true) { ?>
                            <button title="Update Inventory Locations Data" type="button" onclick="setLocation('<?= $updateIvnentoryLocationsUrl ?>')" style="margin:5px;">
                                <span>Update Inventory Locations Data</span>
                            </button>
                        <?php } else { ?>
                            <button class="disabled" type="button" title="No connectivity" onclick="" style="margin:5px;">
                                <span>Update Inventory Locations Data</span>
                            </button>
                        <?php } ?>
                        <table class="admin__table-primary dashboard-data" id="lastOrdersGrid_table">
                            <thead>
                                <tr>
                                    <th class="data-grid-th  no-link"><span>ID</span></th>
                                    <th class="data-grid-th  no-link col-items"><span>Short Name</span></th>
                                    <th class="data-grid-th  no-link col-total"><span>Name</span></th>
                                    <th class="data-grid-th  no-link col-total shrink-col"><span>Address</span></th>
                                    <th class="data-grid-th  no-link col-total"><span>Enabled</span></th>
									<th class="data-grid-th  no-link col-total"><span>Magento Inventory Source</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;

                                foreach ($block->getInventories() as $inventory):
                                    ?>
                                    <?php $source = $block->getSource($inventory); ?>
                                    <tr <?= ($source === -1) ? 'class="bg-disabled"' : ''; ?>>
                                        <td class=" col-customer "><?= $inventory->getId() ?></td>
                                        <td class=" col-items col-number "><?= $inventory->getShortname() ?></td>
                                        <td class=" col-total a-right last"><?= $inventory->getName() ?></td>
                                        <td class=" col-total a-right last"><?= $inventory->getAddress() ?></td>
                                        <td>
                                            <?php if($inventory->getStockSourceCode() != null): ?>
                                                <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/accept.png') ?>" />
                                            <?php endif; ?>
                                        </td>
										
                                        <?php $sourceAssignUrl = $block->getUrl('megaventory/index/assigninventorystock'); ?>
                                        <td id="inventory_source_<?= $inventory->getId(); ?>">
                                            <span class="source_name">
                                                <?= ($source === -1) ? '' : $source->getName(); ?>
                                                <?php if(count($stockSourceCollection) > 0): ?> 
                                                    <a href="javascript:void()" class="assign_new_source" onclick="displayForm('#inventory_source_<?= $inventory->getId(); ?>')">Assign source</a>
                                                <?php endif; ?>
                                                <?php if($source !== -1): ?>
                                                    <a href="javascript:void()" class="remove_source danger" data-trigger="mv_remove_source_<?= $inventory->getId(); ?>" onclick="removeSource(<?= $inventory->getId(); ?>)">Remove Source</a>   
                                                <?php endif; ?>    
                                            </span>
                                            <form class="source_change no-display" action="<?= $sourceAssignUrl; ?>" method="post">
                                                <?= $block->getBlockHtml('formkey')?>
                                                <input type="hidden" name="inventory_id" value="<?= $inventory->getId(); ?>" />
                                                <select class="select admin__control-select" name="source_code">
                                                    <?php foreach($stockSourceCollection as $stockSource): ?>
                                                        <option value="<?= $stockSource->getSourceCode(); ?>" <?= (($source !== -1) && ($source->getSourceCode() === $stockSource->getSourceCode())) ? 'selected' : '' ?> ><?= $stockSource->getName(); ?></option>
                                                    <?php endforeach; ?>    
                                                </select>
                                                <button class="action-primary">Save</button>
                                                <button class="action-secondary" onclick="hideForm('#inventory_source_<?= $inventory->getId(); ?>')">Cancel</button>    
                                            </form>  
                                        </td>
                                    </tr>
                                    <?php $i++;
                                endforeach;
                                ?>
                            </tbody>
                        </table>

                        <br />
                        <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/message.png') ?>" style="position:relative;top:1px;left:4px;margin-right:10px;" />
                        <span>Megaventory location is enabled when it is assigned to a Magento Inventory Source</span>
                        
                        <br /><br />
                        <?php if($orderSyncrhonization == '1'): ?>
                        <div class="mvsettings-container row">
                            <h3>Multi source inventory shipment selection</h3>
                            <form action="<?= $block->getUrl('megaventory/index/algorithmsave'); ?>" method="post">
                                <?= $block->getBlockHtml('formkey')?>
                                <select class="select admin__control-select" name="algorithm_code">
                                    <?php foreach($block->getAlgorithmList() as $algorithm): ?>
                                        <option value="<?= $algorithm['value']; ?>" <?= $algorithm['selected'] ? "selected" : ""; ?>><?= $algorithm['label']; ?></option>
                                    <?php endforeach; ?>    
                                </select>
                                <button class="action-primary">Save</button>
                            </form>
                            <br />
                            <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/message.png') ?>" style="position:relative;top:1px;left:4px;margin-right:10px;" />
                            <span>This is used to decide the preferred location to place the order.</span>
                        </div>
                        <?php endif; ?>


                        <br /><br>
                        <?php if ($connectivityOk === true) { ?>
                            <button id="" type="button" onclick="importInventory(1)" style="">
                                <span>Import Inventory from Megaventory</span>
                            </button>
                            <br /><br />
                            <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/message.png') ?>" style="position:relative;top:1px;left:4px;margin-right:10px;" />
                            <span style="font-weight:bold;">Bulk Import Inventory from Megaventory might be a time consuming task and is required only in exceptional cases.<br />
                                If you enable it make sure your browser has stopped loading before making any further changes anywhere in your Magento.
                            </span>
                            <br /><br />
                            <strong>-OR-</strong><br><br>
                            <button id="export-stock-btn-next" type="button" onclick="exportStock(0)">
                                <span>Export Magento Stock as Megaventory Inventory Adjustment</span>
                            </button>&nbsp;&nbsp;
                            <br /><span id="export-stock-msg"></span>
                            <br /><br />
                            <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/message.png') ?>" style="position:relative;top:1px;left:4px;margin-right:10px;" />
                            <span style="font-weight:bold;">This will create the necessary Inventory Adjustment documents in Megaventory which when Verified <br />
                                will synchronize your current Magento stock with the associated Megaventory Inventory locations.</span>
                            <br /><br />
                            &nbsp;&nbsp;

                        <?php } else { ?>
                            <button id="" type="button" title="No connectivity" onclick="" class="disabled" style="">
                                <span>Import Inventory from Megaventory</span>
                            </button>
                            <br /><br />
                            <strong>-OR-</strong><br><br>
                            <button id="export-stock-btn-next" type="button" title="No connectivity" onclick="" class="disabled">
                                <span>Export Magento Stock as Megaventory Inventory Adjustment</span>
                            </button>&nbsp;&nbsp;
                            <br /><span id="export-stock-msg"></span>
                            <br /><br />
                            <img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/message.png') ?>" style="position:relative;top:1px;left:4px;margin-right:10px;" />
                            <span style="font-weight:bold;">This will create the necessary Inventory Adjustment documents in Megaventory which when Verified <br />
                                will synchronize your current Magento stock with the associated Megaventory Inventory locations.</span>
                            <br /><br />
                            &nbsp;&nbsp;

                        <?php } ?>
                    </div>
                </div>
                <div class="mvsettings-container row" style="height:20px;border-bottom:2px solid grey;margin-bottom:20px;">
                </div>
                <div class="mvsettings-container row">
                    <div class="col-m-12">
                        <div class="admin__legend">Taxes</div>
                        <table class="admin__table-primary dashboard-data">
                            <thead>
                                <tr>
                                    <th class="data-grid-th  no-link"><span>ID</span></th>
                                    <th class="data-grid-th  no-link col-total"><span>Name</span></th>
                                    <th class="data-grid-th  no-link col-total"><span>Description</span></th>
                                    <th class="data-grid-th  no-link col-total"><span>Percentage</span></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;
                                $syncTaxessUrl = $block->getUrl("megaventory/index/synchronizeTaxes");

                                foreach ($block->getTaxes() as $tax):
                                    ?>
                                    <tr>
                                        <td class=" col-customer "><?= $tax->getId() ?></td>
                                        <td class=" col-total a-right last"><?= $tax->getName() ?></td>
                                        <td class=" col-total a-right last"><?= $tax->getDescription() ?></td>
                                        <td class=" col-total a-right last"><?= $tax->getPercentage() ?></td>
                                    </tr>
                                    <?php
                                    $i++;
                                endforeach;
                                ?>
                            </tbody>
                        </table>
                        <br />
                        <?php if ($connectivityOk === true) { ?>
                            <button id="sync-taxes-id" title="Synchronize Taxes" type="button" onclick="setLocation('<?= $syncTaxessUrl ?>')" style="">
                                <span>Synchronize Taxes</span>
                            </button>
                        <?php } else { ?>
                            <button id="sync-taxes-id" title="No connectivity" type="button" onclick="" style="" class="disabled">
                                <span>Synchronize Taxes</span>
                            </button>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
            <div class="mvsettings-container row" style="height:20px;border-bottom:2px solid grey;margin-bottom:20px;">
            </div>
            <div class="mvsettings-container row">
                <div class="col-m-12">
                    <div class="admin__legend">User Manuals</div>
                    <div>
                        <a href="http://www.megaventory.com/Megaventory_Manual.pdf" target="_blank">Megaventory Manual<img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/pdf.png') ?>" style=" position: relative; top: 25px;" /></a><br />
                        <a href="https://www.megaventory.com/Megaventory-Magento-Integration-Instructions.pdf" target="_blank">Megaventory - Magento Integration Manual<img src="<?= $block->getViewFileUrl('Mv_Megaventory::images/pdf.png') ?>" style=" position: relative; top: 25px;" /></a>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div id="response_modal">
        <div class='content'></div>
    </div>
    <div id="confirm_prompt">
        <div class='content'></div>
    </div>    
</div>

<script>
    require(['jquery', 'jquery/ui', 'Magento_Ui/js/form/element/single-checkbox'], function($,check) {
        var selectedSourceValues = [];
        window.checkConnectivity = function() {
            url = "<?= $block->getUrl("megaventory/index/checkConnectivity") ?>";
            new Ajax.Request(url, {
                parameters: {
                    'megaventory_apiurl': $('megaventory_connectivity_apiurl-id').value,
                    'megaventory_apikey': $('megaventory_connectivity_apikey-id').value,
                    'megaventory_enabled': $('megaventory_connectivity_enabled-id')[$('megaventory_connectivity_enabled-id').selectedIndex].value
                },
                onSuccess: function(transport) {
                    location = '<?= $indexURL ?>';
                }
            });
        }

        $("select.inventory").on("change",function(){
            var value = $(this).val();
            var idx = $(this).parent().parent().index();
            var enableBtn = false;

            if(value != 'no_val'){
                selectedSourceValues[idx] = value;
            }
            else{
                selectedSourceValues[idx] = '';
            }

            $("select.inventory").find('option').prop('disabled',false);

            selectedSourceValues.forEach(function(val,index){
                $("select.inventory").not(':eq('+index+')').find('option[value="'+val+'"]').prop('disabled',true);
                if(val != ''){
                    enableBtn = true;
                }
            });

            $("#export-stock-btn").prop('disabled',!enableBtn);
        });

        window.displayForm = function(elem){
            $(elem).find('.source_name').addClass('no-display');
            $(elem).find('.source_change').removeClass('no-display');
        }

        window.hideForm = function(elem){
            window.event.preventDefault();
            $(elem).find('.source_change').addClass('no-display');
            $(elem).find('.source_name').removeClass('no-display');
        }
        
        window.removeSource = function(inventoryId){

            $("#confirm_prompt .content").html('This will remove the association with the magento inventory source and disable the location.');

            $("#confirm_prompt").confirm({
                title: $.mage.__('Are you sure?'),
                actions: {
                    confirm: function(){
                        var url = "<?= $block->getUrl('megaventory/index/removeassignedsource'); ?>";

                        $.ajax({
                            url: url,
                            type: 'POST',
                            showLoader: true,
                            data:{'inventory_id':inventoryId},
                            success: function(data) {
                                $("#response_modal").modal({
                                    'type':'popup',
                                    'title':data.status_label,
                                    'responsive':true,
                                    'buttons':[
                                        {
                                            text:jQuery.mage.__('Ok'),
                                            class:'action-primary'
                                        }
                                    ],
                                    'closed':function(){
                                        location = '<?= $indexURL ?>';
                                    }
                                });
                                $("#response_modal .content").html(data.message);
                                $("#response_modal").modal('openModal');
                            }
                        });      
                    }
                }
            });

        }

		window.syncData = function() {
            $('#megaventory_shipping_sku-id-required').hide();
            $('#megaventory_discount_sku-id-required').hide();

            flag = 0;
            if ($('#megaventory_shipping_sku-id').val().trim() == '') {
                $('#megaventory_shipping_sku-id-required').show();
                flag = 1;
            }
            if ($('#megaventory_discount_sku-id').val().trim() == '') {
                $('#megaventory_discount_sku-id-required').show();
                flag = 1;
            }

            if (flag)
                return;

            $('body').trigger('processStart');

            $('#megaventory_shipping_sku-id').addClass('disabled');
            $('#megaventory_discount_sku-id').addClass('disabled');
            $('#megaventory_shipping_sku-id').prop('disabled', true);
            $('#megaventory_discount_sku-id').prop('disabled', true);

            var updateSKUs = "<?= $block->getUrl("megaventory/index/setshippinganddiscountskus") ?>";

            $.ajax({
                url: updateSKUs,
                type: 'POST',
                data: {
                    shippingSKU: $('#megaventory_shipping_sku-id').val(),
                    discountSKU: $('#megaventory_discount_sku-id').val(),
                    magentoId: $('#megaventory_magento_id-id').val(),
                    magento_supplier_code: $('#megaventory_supplier-id').val()
                },
                dataType: 'json',
                //showLoader: true,
                success: function(result, status) {
                    if (result.html) {
                        $("#response_modal").modal({
                            'type':'popup',
                            'title':'SKUs Updated Successfully',
                            'responsive':true,
                            'buttons':[
                                {
                                    text:jQuery.mage.__('Ok'),
                                    class:'action-primary'
                                }
                            ],
                            'closed':function(){
                                location = '<?= $indexURL ?>';
                            }
                        });
                        $("#response_modal .content").html(result.html);
                        $("#response_modal").modal('openModal');
                        
                    } else {
                        continueSyncData();
                    }
                }
            });

        }

        var progressTimeOut = true;

        window.getProgress = function() {
            var url = "<?= $block->getUrl("megaventory/index/getProgress") ?>";

            $.ajax({
                url: url,
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    var html = data.message;
                    $('#sync-data-progress-id').html(html);
                    if (data.step == 'done') {
                        clearTimeout(progressTimeout);
                        progressTimeout = false;
                    }
                },
                complete: function(data) {
                    // schedule the next request *only* when the current one is complete:
                    if (progressTimeout)
                        setTimeout(getProgress, 1000);
                }
            });
        }

        window.continueSyncData = function() {

            $('#sync-heading-id').html('Initialization process started.Please do not close browser window while initialization runs');
            $('#sync-data-btn').hide();

            sync('inventories', '1', 0);

            progressTimeout = setTimeout(getProgress, 1000);
        }

        window.sync = function(step, page, imported) {
            var url = "<?= $block->getUrl("megaventory/index/syncData") ?>";

            $.ajax({
                url: url,
                type: 'GET',
                data: {
                    step: step,
                    page: page,
                    imported: imported
                },
                dataType: 'json',
                success: function(data) {
                    if (data.nextstep != 'finish' && data.nextstep != 'finisherror') {
                        sync(data.nextstep, data.nextpage, data.imported);
                    } else {
                        if (data.nextstep != 'finisherror') {
                            next1Setup();
                            //$('next-step').show();
                        } else
                            $('next-error').show();
                    }
                }
            });
        }


        window.resetSetup = function() {
            $("#confirm_prompt .content").html('Reseting Setup will delete all Megaventory data from your Magento installation.Are you sure you want to proceed?');

            $("#confirm_prompt").confirm({
                title: $.mage.__('Are you sure?'),
                actions: {
                    confirm: function(){
                        url = "<?= $block->getUrl("megaventory/index/resetSetup") ?>";

                        $.ajax({
                            url: url,
                            type: 'GET',
                            showLoader: true,
                            success: function(data) {
                                $("#response_modal").modal({
                                    'type':'popup',
                                    'title':'Setup has been reset',
                                    'responsive':true,
                                    'buttons':[
                                        {
                                            text:jQuery.mage.__('Ok'),
                                            class:'action-primary'
                                        }
                                    ],
                                    'closed':function(){
                                        location = '<?= $indexURL ?>';
                                    }
                                });
                                $("#response_modal").modal('openModal');
                            }
                        });      
                    }
                }
            });
        }

        window.confirmSetLocation = function(message, location) {
            var r = confirm(message);
            if (r == true) {
                setLocation(location);
            }
        }

        window.next1Setup = function() {
            url = "<?= $block->getUrl("megaventory/index/getInventories") ?>";

            $.ajax({
                url: url,
                type: 'GET',
                success: function(data) {
                    //$('#initial-stock-inventory-id').html(data.options);

                    $(".inventory").empty();

                    var option = $('<option></option>').attr("value", 'no_val').text('(Do not sync)');
                    $(".inventory").append(option);

                    for (i = 0; i < data.options.length; i++) {
                        var option = $('<option></option>').attr("value", data.options[i].value).text(data.options[i].text);
                        $(".inventory").append(option);
                    }

                    $('#next-step').show();
                    $('body').trigger('processStop');
                }
            });
        }

        window.exportStock = function(startingIndex, adj = false) {
            url = "<?= $block->getUrl("megaventory/index/exportStock") ?>";

            $.ajax({
                url: url,
                type: 'POST',
                showLoader: true,
                data: {
                    startingIndex: startingIndex,
                    init:0,
                    adjustment: adj
                },
                dataType: 'json',
                success: function(data) {

                    if (data.value == 'Continue') {

                        exportStock(data.startingIndex, data.adjMade);

                    } else {
                        $("#response_modal").modal({
                            'type':'popup',
                            'title':data.value,
                            'responsive':true,
                            'buttons':[
                                {
                                    text:jQuery.mage.__('Ok'),
                                    class:'action-primary'
                                }
                            ]
                        });
                        $("#response_modal .content").html(data.message);
                        $("#response_modal").modal('openModal');
                    }
                }
            });
        }


        window.exportStockAndFinish = function(startingIndex, adj = false) {
            url = "<?= $block->getUrl("megaventory/index/exportStock") ?>";
            locations = $("select.inventory");
            sources = $("input.source");
            locs = {};
            data = {startingIndex:startingIndex, adjustment:adj};

            sources.each(function(index,currentSource){
                locationValue = locations.eq(index).val();
                if(locationValue != 'no_val'){
                    locs[locationValue] = currentSource.value;
                }
            });
            data['locations'] = locs;
            data['init'] = 1;
            $.ajax({
                url: url,
                type: 'POST',
                showLoader: true,
                data: data,
                dataType: 'json',
                success: function(data) {
                    if (data.value == 'Continue') {

                        exportStockAndFinish(data.startingIndex,data.adjMade);

                    } else {
                        $("#response_modal").modal({
                            'type':'popup',
                            'title':data.value,
                            'responsive':true,
                            'buttons':[
                                {
                                    text:jQuery.mage.__('Ok'),
                                    class:'action-primary'
                                }
                            ],
                            'closed':function(){
                                $('#finish-btn').show();
                                $('#cancel-export-stock').hide();
                                $("#export-stock-btn").hide();
                            }
                        });
                        $("#response_modal .content").html(data.message);
                        $("#response_modal").modal('openModal');
                    }

                },
                error: function(error) {
                    $("#response_modal").modal({
                        'type':'popup',
                        'title':'Error',
                        'responsive':true,
                        'buttons':[
                            {
                                text:jQuery.mage.__('Ok'),
                                class:'action-primary'
                            }
                        ]
                    });
                    $("#response_modal .content").html('An error occurred while saving the data.');
                    $("#response_modal").modal('openModal');
                }
            });
        }

        window.checkOrderSynchronization = function(oneOrZero, checkBox) {

            var url = "<?= $block->getUrl("megaventory/index/updateOrderSynchronization"); ?>";

            $("#confirm_prompt .content").html('This will modify the order synchronization option.');

            $("#confirm_prompt").confirm({
                title: $.mage.__('Are you sure?'),
                actions: {
                    confirm: function(){
                        $.ajax({
                            url: url,
                            type: 'POST',
                            showLoader: true,
                            data: {
                                value: oneOrZero
                            },
                            dataType: 'json',
                            success: function(data) {
                                $("#response_modal").modal({
                                    'type':'popup',
                                    'title':'Success',
                                    'responsive':true,
                                    'buttons':[
                                        {
                                            text:jQuery.mage.__('Ok'),
                                            class:'action-primary'
                                        }
                                    ],
                                    'closed':function(){
                                        location = '<?= $indexURL ?>';
                                    }
                                });
                                $("#response_modal .content").html('The setting has been changed successfully.');
                                $("#response_modal").modal('openModal');
                            },
                            error: function(error) {
                                $("#response_modal").modal({
                                    'type':'popup',
                                    'title':'Error',
                                    'responsive':true,
                                    'buttons':[
                                        {
                                            text:jQuery.mage.__('Ok'),
                                            class:'action-primary'
                                        }
                                    ],
                                    'closed':function(){
                                        location = '<?= $indexURL ?>';
                                    }
                                });
                                $("#response_modal .content").html('Unable to save the configuration.');
                                $("#response_modal").modal('openModal');
                            }
                        });
                    },
                    cancel: function(){
                        checkBox.checked = !checkBox.checked;
                    }
                }
            });
        }

        window.updateSupplierSettings = function() {
            url = "<?= $block->getUrl("megaventory/index/updateSupplierSettings") ?>";

            $.ajax({
                url: url,
                type: 'POST',
                showLoader: true,
                data: {
                    magento_supplier_code: $('#megaventory_supplier-id').val()
                },
                dataType: 'json',
                success: function(data) {
                    $("#response_modal").modal({
                        'type':'popup',
                        'title':'Success',
                        'responsive':true,
                        'buttons':[
                            {
                                text:jQuery.mage.__('Ok'),
                                class:'action-primary'
                            }
                        ],
                        'closed':function(){
                            setLocation('<?= $indexURL ?>');
                        }
                    });
                    $("#response_modal .content").html(data.message);
                    $("#response_modal").modal('openModal');
                },
                error: function(error) {
                    $("#response_modal").modal({
                        'type':'popup',
                        'title':'Error',
                        'responsive':true,
                        'buttons':[
                            {
                                text:jQuery.mage.__('Ok'),
                                class:'action-primary'
                            }
                        ]
                    });
                    $("#response_modal .content").html('An error occurred while saving the data.');
                    $("#response_modal").modal('openModal');
                }
            });
        }

        window.updateMagentoId = function() {
            url = "<?= $block->getUrl("megaventory/index/updateMagentoId") ?>";

            $.ajax({
                url: url,
                type: 'POST',
                showLoader: true,
                data: {
                    magento_id: $('#megaventory_magento_id-id').val()
                },
                dataType: 'json',
                success: function(data) {
                    $("#response_modal").modal({
                        'type':'popup',
                        'title':'Success',
                        'responsive':true,
                        'buttons':[
                            {
                                text:jQuery.mage.__('Ok'),
                                class:'action-primary'
                            }
                        ]
                    });
                    $("#response_modal .content").html(data.message);
                    $("#response_modal").modal('openModal');
                }
            });
        }

        window.importInventory = function(page) {
            $("#confirm_prompt .content").html('This action will recalculate global magento quantities based on the quantities of the selected inventory locations of your megaventory account. Proceed only if you understand this warning.');
            $("#confirm_prompt").confirm({
                title: $.mage.__('Are you sure?'),
                actions: {
                    confirm: function(){
                        url = "<?= $syncIvnentoriesUrl ?>";

                        $.ajax({
                            url: url,
                            type: 'POST',
                            showLoader: true,
                            data: {
                                'page': page
                            },
                            dataType: 'json',
                            success: function(data) {
                                if (data.page != -1) {
                                    importInventoryNoConfirm(data.page);
                                } else {
                                    $("#response_modal").modal({
                                        'type':'popup',
                                        'title':'Success',
                                        'responsive':true,
                                        'buttons':[
                                            {
                                                text:jQuery.mage.__('Ok'),
                                                class:'action-primary'
                                            }
                                        ]
                                    });
                                    $("#response_modal .content").html('Inventory imported successfully!');
                                    $("#response_modal").modal('openModal');
                                }
                            }
                        });
                    }
                }
            });
        }

        window.importInventoryNoConfirm = function(page) {
            url = "<?= $syncIvnentoriesUrl ?>";

            $.ajax({
                url: url,
                type: 'POST',
                showLoader: true,
                data: {
                    'page': page
                },
                dataType: 'json',
                success: function(data) {
                    if (data.page != -1) {
                        importInventoryNoConfirm(data.page);
                    } else {
                        $("#response_modal").modal({
                            'type':'popup',
                            'title':'Success',
                            'responsive':true,
                            'buttons':[
                                {
                                    text:jQuery.mage.__('Ok'),
                                    class:'action-primary'
                                }
                            ]
                        });
                        $("#response_modal .content").html('Inventory imported successfully!');
                        $("#response_modal").modal('openModal');
                    }
                }
            });
        }
    });
</script>
